import { ScreenshotSlot } from '@/ui'
import { Reveal } from './Reveal'
import { SHOWCASE_ITEMS } from './content'
import styles from './ShowcaseSection.module.css'

/** Gallery of real captures of the studio, regenerated by `scripts/capture-shots.mjs`. */
export function ShowcaseSection() {
  return (
    <section className={styles.showcase} aria-label="Screenshots">
      <Reveal className={styles.heading}>
        <h2 className={styles.title}>See it in the studio</h2>
        <p className={styles.body}>
          Every shot below is the app itself, captured as it ships.
        </p>
      </Reveal>

      <div className={styles.gallery}>
        {SHOWCASE_ITEMS.map((item, index) => (
          <Reveal key={item.caption} delay={index * 80}>
            <ScreenshotSlot caption={item.caption} src={item.src} aspect="wide" />
          </Reveal>
        ))}
      </div>
    </section>
  )
}
