import { cx } from '@/lib/cx'
import styles from './ScreenshotSlot.module.css'

export interface ScreenshotSlotProps {
  /** Shown under the frame, and as the image's alt text unless `alt` is given. */
  caption: string
  /** The screenshot to display. Generated by `scripts/capture-shots.mjs`. */
  src: string
  alt?: string
  aspect?: 'wide' | 'tall' | 'square'
  className?: string | undefined
}

/**
 * A framed screenshot with a caption.
 *
 * This used to render a placeholder when `src` was omitted, so the pages could
 * be built before any real imagery existed. Every slot now has a real capture,
 * so `src` is required — the placeholder's job is done, and leaving it in
 * would let a future slot ship silently empty.
 */
export function ScreenshotSlot({
  caption,
  src,
  alt = caption,
  aspect = 'wide',
  className,
}: ScreenshotSlotProps) {
  return (
    <figure className={cx(styles.slot, className)}>
      <div className={cx(styles.frame, styles[aspect])}>
        <img className={styles.image} src={src} alt={alt} loading="lazy" />
      </div>
      <figcaption className={styles.caption}>{caption}</figcaption>
    </figure>
  )
}
